DROP TABLE IF EXISTS UserData;

CREATE TABLE UserData (
    UserID INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Username TEXT NOT NULL UNIQUE,
    HashedPassword VARCHAR(72) NOT NULL,
    Salt TEXT NOT NULL
);
DROP TABLE IF EXISTS FriendsTable;

CREATE TABLE FriendsTable(
    LinkID INTEGER PRIMARY KEY AUTOINCREMENT,
    User1ID INTEGER,
    User2ID INTEGER,
    Status TEXT NOT NULL
);
DROP TABLE IF EXISTS MessageTable;
CREATE TABLE MessageTable(
  LinkID INTEGER PRIMARY KEY AUTOINCREMENT,
  SenderID INTEGER NOT NULL,
  ReceiverID INTEGER NOT NULL,
  messageTimeStamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  messageContent CHAR(255) NOT NULL
);

DROP TABLE IF EXISTS GroupChatData;
CREATE TABLE GroupChatData(
  GroupChatID INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  GroupChatName TEXT Not Null UNIQUE,
  creator INTEGER NOT NULL
);

DROP TABLE IF EXISTS GroupChatUsers;
CREATE TABLE GroupChatUsers(
  ChatUsersID INTEGER PRIMARY KEY AUTOINCREMENT,
  GroupChatName TEXT Not Null UNIQUE,
  UserID INTEGER NOT NULL,
  UserName Text NOT Null
);

DROP TABLE IF EXISTS GroupChatMessages;
CREATE TABLE GroupChatMessages(
  ChatMessages INTEGER PRIMARY KEY AUTOINCREMENT,
  GroupChatID INTEGER NOT NULL,
  SenderID INTEGER NOT NULL,
  Message CHAR(255) NOT NULL,
  ChatTimeStamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);